name: cardapp
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  http: ^0.13.4
  translator: ^0.1.7
  flutter_image: ^4.0.17
  image: ^4.0.17
  url_launcher: ^6.1.11
  # path: ^1.8.0


dev_dependencies:
 
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.2.0

flutter:
  uses-material-design: true